/**
 * WPAG Participant Application Types
 *
 * Central type definitions for participant application submission,
 * validation, database persistence, eligibility review creation,
 * and API responses.
 */

export const APPLICATION_STATUS = {
  DRAFT: "draft",
  SUBMITTED: "submitted",
  UNDER_REVIEW: "under_review",
  ELIGIBILITY_APPROVED: "eligibility_approved",
  ELIGIBILITY_REJECTED: "eligibility_rejected",
  MORE_INFORMATION_REQUIRED: "more_information_required",
  PARTICIPANT_CREATED: "participant_created",
} as const;

export type ApplicationStatus =
  (typeof APPLICATION_STATUS)[keyof typeof APPLICATION_STATUS];

export const ELIGIBILITY_REVIEW_STATUS = {
  PENDING: "pending",
  IN_PROGRESS: "in_progress",
  COMPLETED: "completed",
} as const;

export type EligibilityReviewStatus =
  (typeof ELIGIBILITY_REVIEW_STATUS)[keyof typeof ELIGIBILITY_REVIEW_STATUS];

export const ELIGIBILITY_DECISION = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  MORE_INFORMATION_REQUIRED: "more_information_required",
} as const;

export type EligibilityDecision =
  (typeof ELIGIBILITY_DECISION)[keyof typeof ELIGIBILITY_DECISION];

/**
 * Payload received from the participant application form.
 *
 * Gender is intentionally excluded from the initial application.
 * It may be collected optionally during the participant profile stage.
 */
export interface CreateApplicationRequest {
  fullName: string;
  email: string;

  phoneCountryCode: string;
  phoneNumber: string;

  countryCode: string;
  countryName?: string;

  stateOrRegion?: string;
  city?: string;

  timezone?: string;
  preferredLanguage?: string;

  ageGroup?: string;
  employmentStatus?: string;

  applicationReason: string;
  financialChallenges?: string;
  expectations?: string;
  referralSource?: string;

  privacyAcknowledged: boolean;
}

/**
 * Normalized application data after validation.
 *
 * The validator will trim text, lowercase email,
 * normalize country codes, and remove empty optional values.
 */
export interface NormalizedApplicationInput {
  fullName: string;
  email: string;

  phoneCountryCode: string;
  phoneNumber: string;

  countryCode: string;
  countryName: string | null;

  stateOrRegion: string | null;
  city: string | null;

  timezone: string | null;
  preferredLanguage: string | null;

  ageGroup: string | null;
  employmentStatus: string | null;

  applicationReason: string;
  financialChallenges: string | null;
  expectations: string | null;
  referralSource: string | null;

  privacyAcknowledged: true;
}

/**
 * Metadata captured by the API route.
 */
export interface ApplicationRequestMetadata {
  sourceIp: string | null;
  userAgent: string | null;
  authUserId: string | null;
}

/**
 * Application record returned after database insertion.
 *
 * applicationCode is generated by PostgreSQL/Supabase.
 */
export interface CreatedApplicationRecord {
  id: string;
  applicationCode: string;
  status: ApplicationStatus;
  submittedAt: string | null;
  createdAt: string;
}

/**
 * Eligibility review record automatically created
 * after an application is submitted.
 */
export interface CreatedEligibilityReviewRecord {
  id: string;
  applicationId: string;
  reviewNumber: number;
  reviewStatus: EligibilityReviewStatus;
  decision: EligibilityDecision;
  createdAt: string;
}

export interface ApplicationSubmissionResult {
  application: CreatedApplicationRecord;
  eligibilityReview: CreatedEligibilityReviewRecord;
}

/**
 * Field-level validation error.
 */
export interface ApplicationValidationError {
  field: keyof CreateApplicationRequest | "request";
  message: string;
}

/**
 * Validator success result.
 */
export interface ApplicationValidationSuccess {
  valid: true;
  data: NormalizedApplicationInput;
  errors: [];
}

/**
 * Validator failure result.
 */
export interface ApplicationValidationFailure {
  valid: false;
  data: null;
  errors: ApplicationValidationError[];
}

export type ApplicationValidationResult =
  | ApplicationValidationSuccess
  | ApplicationValidationFailure;

/**
 * Successful API response.
 */
export interface CreateApplicationSuccessResponse {
  success: true;
  applicationId: string;
  applicationCode: string;
  status: ApplicationStatus;
  message: string;
}

/**
 * Failed API response.
 */
export interface CreateApplicationErrorResponse {
  success: false;
  message: string;
  errors?: ApplicationValidationError[];
}

export type CreateApplicationResponse =
  | CreateApplicationSuccessResponse
  | CreateApplicationErrorResponse;