import Link from "next/link";
import { notFound } from "next/navigation";

import AdminEvidenceVerificationPanel from "@/components/admin/evidence/AdminEvidenceVerificationPanel";
import { getAdminEvidenceDownloadActions } from "@/components/admin/evidence/admin-evidence-action-policy";
import { requireRole } from "@/lib/auth/authorization";
import { adminEvidenceVerificationService, AdminEvidenceVerificationServiceError } from "@/lib/services/admin/admin-evidence-verification-service";

function label(value: string | null) { return value ? value.split("_").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ") : "—"; }
function date(value: string | null) { return value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
function bytes(value: number) { return value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KiB` : `${(value / 1024 / 1024).toFixed(1)} MiB`; }

export default async function AdminEvidenceDetailPage({ params }: { params: Promise<{ documentId: string }> }) {
  const staff = await requireRole("administrator");
  const { documentId } = await params;
  let evidence;
  try { evidence = await adminEvidenceVerificationService.get(documentId, staff.auth_user_id); }
  catch (error) { if (error instanceof AdminEvidenceVerificationServiceError && error.kind === "not_found") notFound(); throw error; }
  return <main className="min-h-screen bg-black px-4 py-10 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl">
    <nav className="flex flex-wrap gap-5 text-sm"><Link href="/admin/evidence" className="text-white/50 hover:text-white">← Back to Evidence Queue</Link><Link href={`/admin/participants/${evidence.participantId}`} className="text-sky-300">Participant Workspace</Link><Link href={`/admin/reviews/assessments/${evidence.assessmentId}`} className="text-sky-300">Assessment Review</Link></nav>
    <header className="mt-8 border-b border-white/10 pb-8"><p className="text-xs uppercase tracking-[0.3em] text-white/40">Evidence Verification</p><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">{evidence.displayName}</h1><p className="mt-3 text-sm text-white/50">{evidence.participantName} · {evidence.participantCode} · Assessment #{evidence.assessmentNumber}</p></div><span className="rounded-full border border-white/10 px-4 py-2 text-sm">{label(evidence.verificationStatus)}</span></div></header>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Category",label(evidence.documentCategory)],["Type",label(evidence.documentType)],["Current version",`v${evidence.currentVersion}`],["File",`${evidence.originalFilename} · ${bytes(evidence.fileSizeBytes)}`],["Submitted",date(evidence.submittedAt)],["Updated",date(evidence.updatedAt)],["Reviewer",evidence.reviewedBy ?? "—"],["Reviewed",date(evidence.verificationAt)]].map(([name,value]) => <article key={name} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-xs uppercase tracking-wider text-white/35">{name}</p><p className="mt-3 break-words text-sm text-white/80">{value}</p></article>)}</section>
    {evidence.participantComment ? <section className="mt-8 rounded-2xl border border-amber-400/20 bg-amber-400/[0.05] p-6"><h2 className="font-semibold">Participant-visible feedback</h2><p className="mt-3 whitespace-pre-wrap text-sm text-white/70">{evidence.participantComment}</p></section> : null}
    <AdminEvidenceVerificationPanel evidence={evidence} />
    <section className="mt-8 rounded-2xl border border-white/10 bg-white/[0.02] p-6"><h2 className="text-lg font-semibold">Immutable File Versions</h2><div className="mt-5 space-y-3">{evidence.versions.map((version) => { const actions = getAdminEvidenceDownloadActions(evidence.documentId, version.versionNumber, evidence.canDownload); return <article key={version.versionNumber} className="flex flex-col gap-3 rounded-xl border border-white/10 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p>{version.originalFilename} · v{version.versionNumber}</p><p className="mt-1 text-xs text-white/40">{label(version.mimeType)} · {bytes(version.fileSizeBytes)} · {date(version.submittedAt)}</p></div>{actions.length > 0 ? <div className="flex gap-3">{actions.map((action) => <a key={action.label} href={action.href} target={action.label === "Preview" ? "_blank" : undefined} rel={action.label === "Preview" ? "noreferrer" : undefined} className="text-sm text-sky-300">{action.label}</a>)}</div> : null}</article>; })}</div></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.02] p-6"><h2 className="text-lg font-semibold">Verification History</h2><div className="mt-5 space-y-4">{evidence.verificationHistory.map((event, index) => <article key={`${event.eventAt}-${index}`} className="border-l border-white/10 pl-4"><p className="font-medium">{label(event.verificationEvent)}</p><p className="mt-1 text-xs text-white/40">{date(event.eventAt)} · {event.reviewerName ?? "System/participant"}</p>{event.participantComment ? <p className="mt-2 text-sm text-amber-200/80">Participant: {event.participantComment}</p> : null}{event.internalNotes ? <p className="mt-2 text-sm text-white/60">Internal: {event.internalNotes}</p> : null}</article>)}</div></div><div className="rounded-2xl border border-white/10 bg-white/[0.02] p-6"><h2 className="text-lg font-semibold">Activity History</h2><div className="mt-5 space-y-4">{evidence.activityHistory.map((event, index) => <article key={`${event.eventAt}-${index}`}><p className="font-medium">{event.eventTitle}</p><p className="mt-1 text-xs text-white/40">{date(event.eventAt)}</p>{event.eventDescription ? <p className="mt-2 text-sm text-white/60">{event.eventDescription}</p> : null}</article>)}</div></div></section>
  </div></main>;
}
