import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks=vi.hoisted(()=>({user:vi.fn(),participant:vi.fn(),context:vi.fn(),submit:vi.fn(),resubmit:vi.fn(),download:vi.fn()}));
vi.mock("@/lib/auth/current-participant",()=>({getCurrentUser:mocks.user,getCurrentParticipant:mocks.participant}));
vi.mock("@/lib/services/participant/participant-evidence-foundation-service",()=>{
 class ParticipantEvidenceFoundationServiceError extends Error{constructor(readonly kind:string){super(kind==="unsupported"?"Evidence file format is unsupported or does not match its content.":kind==="oversized"?"Evidence file exceeds the 10 MiB limit.":kind==="not_found"?"Evidence was not found.":kind==="conflict"?"Evidence cannot be changed in its current state.":"Evidence operation could not be completed.");}}
 return{ParticipantEvidenceFoundationServiceError,participantEvidenceFoundationService:{context:mocks.context,submit:mocks.submit,resubmit:mocks.resubmit,download:mocks.download}};
});
import { AuthenticationError } from "@/lib/auth/errors";
import { ParticipantEvidenceFoundationServiceError } from "@/lib/services/participant/participant-evidence-foundation-service";
import { POST as upload } from "./upload/route";
import { POST as resubmit } from "./[documentId]/resubmit/route";
import { GET as download } from "./[documentId]/download/route";

const actorId="20000000-0000-4000-8000-000000000001",assessmentId="10000000-0000-4000-8000-000000000001",documentId="30000000-0000-4000-8000-000000000001";
function uploadRequest(file=new File(["%PDF-test"],"statement.pdf",{type:"application/pdf"})){const form=new FormData();form.set("assessmentId",assessmentId);form.set("documentCategory","income");form.set("documentType","bank_statement");form.set("displayName","Statement");form.set("file",file);return new Request("http://localhost/api/participant/evidence/upload",{method:"POST",body:form});}
describe("participant evidence routes",()=>{
 beforeEach(()=>{vi.resetAllMocks();mocks.user.mockResolvedValue({id:actorId});mocks.participant.mockResolvedValue({lifecycle_status:"active"});mocks.context.mockResolvedValue({assessmentId});mocks.submit.mockResolvedValue({documentId});mocks.resubmit.mockResolvedValue({documentId,versionNumber:2});mocks.download.mockResolvedValue({reference:{originalFilename:"statement.pdf",mimeType:"application/pdf"},bytes:new TextEncoder().encode("%PDF-test")});});
 it("authenticates before multipart parsing",async()=>{mocks.user.mockRejectedValue(new AuthenticationError());const request={formData:vi.fn()} as never;const response=await upload(request);expect(response.status).toBe(401);expect((request as {formData:ReturnType<typeof vi.fn>}).formData).not.toHaveBeenCalled();});
 it("rejects missing fields and unsupported MIME safely",async()=>{const missing=new FormData();missing.set("file",new File(["x"],"x.pdf",{type:"application/pdf"}));expect((await upload(new Request("http://localhost",{method:"POST",body:missing}))).status).toBe(400);expect((await upload(uploadRequest(new File(["x"],"x.txt",{type:"text/plain"})))).status).toBe(415);});
 it("rejects oversized evidence before the service reads bytes",async()=>{const response=await upload(uploadRequest(new File([new Uint8Array(10*1024*1024+1)],"large.pdf",{type:"application/pdf"})));expect(response.status).toBe(413);expect(mocks.submit).not.toHaveBeenCalled();});
 it("executes a successful upload with no-store response",async()=>{const response=await upload(uploadRequest());expect(response.status).toBe(201);expect(response.headers.get("cache-control")).toBe("private, no-store");expect(mocks.submit).toHaveBeenCalledWith(expect.objectContaining({assessmentId,actorUserId:actorId,originalFilename:"statement.pdf",mimeType:"application/pdf",bytes:expect.any(Uint8Array)}));});
 it("maps signature and lifecycle failures without diagnostics",async()=>{mocks.submit.mockRejectedValueOnce(new ParticipantEvidenceFoundationServiceError("unsupported"));expect((await upload(uploadRequest())).status).toBe(415);mocks.submit.mockRejectedValueOnce(new ParticipantEvidenceFoundationServiceError("conflict"));expect((await upload(uploadRequest())).status).toBe(409);});
 it("rejects a mismatched assessment before file submission",async()=>{mocks.context.mockResolvedValue({assessmentId:"40000000-0000-4000-8000-000000000001"});expect((await upload(uploadRequest())).status).toBe(404);expect(mocks.submit).not.toHaveBeenCalled();});
 it("runs resubmission only for the authenticated participant",async()=>{const form=new FormData();form.set("file",new File(["%PDF-new"],"new.pdf",{type:"application/pdf"}));const response=await resubmit(new Request("http://localhost",{method:"POST",body:form}),{params:Promise.resolve({documentId})});expect(response.status).toBe(200);expect(mocks.resubmit).toHaveBeenCalledWith(expect.objectContaining({documentId,actorUserId:actorId}));mocks.resubmit.mockRejectedValueOnce(new ParticipantEvidenceFoundationServiceError("conflict"));expect((await resubmit(new Request("http://localhost",{method:"POST",body:form}),{params:Promise.resolve({documentId})})).status).toBe(409);});
 it("serves governed downloads with private attachment headers",async()=>{const response=await download(new Request(`http://localhost/api/participant/evidence/${documentId}/download?version=2`),{params:Promise.resolve({documentId})});expect(response.status).toBe(200);expect(mocks.download).toHaveBeenCalledWith(documentId,actorId,2);expect(response.headers.get("content-disposition")).toBe('attachment; filename="statement.pdf"');expect(response.headers.get("cache-control")).toBe("private, no-store");expect(response.headers.get("x-content-type-options")).toBe("nosniff");});
 it("denies unauthenticated, missing, and integrity-failed downloads",async()=>{mocks.user.mockRejectedValueOnce(new AuthenticationError());expect((await download(new Request("http://localhost"),{params:Promise.resolve({documentId})})).status).toBe(401);mocks.download.mockRejectedValueOnce(new ParticipantEvidenceFoundationServiceError("not_found"));expect((await download(new Request("http://localhost"),{params:Promise.resolve({documentId})})).status).toBe(404);mocks.download.mockRejectedValueOnce(new ParticipantEvidenceFoundationServiceError("integrity"));expect((await download(new Request("http://localhost"),{params:Promise.resolve({documentId})})).status).toBe(500);});
});
