import { supabaseAdmin } from "@/lib/supabase/admin";
import { researchHistoryFamilies, type AdminResearchWave4Overview, type ResearchHistoryFamily, type ResearchHistoryPage } from "@/lib/types/research/research-wave4";
type Row = { enrollment_id: string; evidence_versions: Array<Record<string, unknown>>; snapshots: Array<Record<string, unknown>>; follow_ups: Array<Record<string, unknown>>; raw_observations: Array<Record<string, unknown>>; verified_events: Array<Record<string, unknown>>; research_outcomes: Array<Record<string, unknown>>; audit_events: Array<Record<string, unknown>>; actor_permissions: Record<string, boolean>; consent_wording_review_status: "APPROVED_WITH_NON_BLOCKING_GOVERNANCE_NOTES"; release_gate_status: "BLOCKED" };
type HistoryRow = { enrollment_id: string; history_family: string; items: unknown; next_cursor_at: string | null; next_cursor_id: string | null; has_more: boolean };
export class AdminResearchWave4RepositoryError extends Error { constructor(readonly kind: "unauthorized" | "invalid" | "unexpected") { super("Wave 4 research operation could not be completed."); } }
function fail(error: { code?: string; message?: string }): never { throw new AdminResearchWave4RepositoryError(error.code === "P1001" && error.message?.includes("not authorized") ? "unauthorized" : error.code === "P1001" ? "invalid" : "unexpected"); }
function map(row: Row): AdminResearchWave4Overview { if (row.consent_wording_review_status !== "APPROVED_WITH_NON_BLOCKING_GOVERNANCE_NOTES" || row.release_gate_status !== "BLOCKED") throw new AdminResearchWave4RepositoryError("unexpected"); return { enrollmentId: row.enrollment_id, evidenceVersions: row.evidence_versions ?? [], snapshots: row.snapshots ?? [], followUps: row.follow_ups ?? [], rawObservations: row.raw_observations ?? [], verifiedEvents: row.verified_events ?? [], researchOutcomes: row.research_outcomes ?? [], auditEvents: row.audit_events ?? [], actorPermissions: row.actor_permissions ?? {}, consentWordingReviewStatus: row.consent_wording_review_status, releaseGateStatus: row.release_gate_status }; }
export function mapResearchHistoryPage(row: HistoryRow): ResearchHistoryPage {
  if (!researchHistoryFamilies.includes(row.history_family as never) || !Array.isArray(row.items) || typeof row.has_more !== "boolean"
    || ((row.next_cursor_at === null) !== (row.next_cursor_id === null)) || (row.has_more && (!row.next_cursor_at || !row.next_cursor_id))) throw new AdminResearchWave4RepositoryError("unexpected");
  return { enrollmentId: row.enrollment_id, historyFamily: row.history_family as ResearchHistoryFamily, items: row.items as Array<Record<string, unknown>>, nextCursorAt: row.next_cursor_at, nextCursorId: row.next_cursor_id, hasMore: row.has_more };
}
export class AdminResearchWave4Repository {
  async get(participantId: string, actorUserId: string, correlationId: string) { const { data,error }=await supabaseAdmin.rpc("get_admin_research_wave4_overview",{p_participant_id:participantId,p_actor_user_id:actorUserId,p_correlation_id:correlationId}); if(error)fail(error); const row=((data??[]) as Row[])[0]; return row?map(row):null; }
  async getHistoryPage(participantId: string, actorUserId: string, family: ResearchHistoryFamily, cursorAt: string | null, cursorId: string | null, limit: number, correlationId: string) { const {data,error}=await supabaseAdmin.rpc("get_admin_research_history_page",{p_participant_id:participantId,p_actor_user_id:actorUserId,p_history_family:family,p_cursor_at:cursorAt,p_cursor_id:cursorId,p_limit:limit,p_correlation_id:correlationId});if(error)fail(error);const row=((data??[]) as HistoryRow[])[0];return row?mapResearchHistoryPage(row):null; }
  async present(enrollmentId: string, actorUserId: string, correlationId: string) { const {data,error}=await supabaseAdmin.rpc("present_wave4_synthetic_research_consent",{p_enrollment_id:enrollmentId,p_actor_user_id:actorUserId,p_correlation_id:correlationId}); if(error)fail(error); return ((data??[]) as Array<Record<string,unknown>>)[0]??null; }
  async attemptActivation(target: string, actorUserId: string, correlationId: string) { const {data,error}=await supabaseAdmin.rpc("attempt_wave4_release_activation",{p_target:target,p_actor_user_id:actorUserId,p_correlation_id:correlationId}); if(error)fail(error); return ((data??[]) as Array<Record<string,unknown>>)[0]??null; }
}
export const adminResearchWave4Repository = new AdminResearchWave4Repository();
