import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/supabase/admin", async () => ({ supabaseAdmin: (await import("@/test/mocks/supabase-admin")).supabaseAdminMock }));

import { AdminPreliminaryReportService, AdminPreliminaryReportServiceError } from "@/lib/services/admin/admin-preliminary-report-service";
import { createInitialPreliminaryReportContent } from "@/lib/types/preliminary-report";
import { errorResult, resetSupabaseAdminMock, setRpcResult, successfulResult, supabaseAdminSpies } from "@/test/mocks/supabase-admin";

const actorId = "10000000-0000-4000-8000-000000000001";
const assessmentId = "20000000-0000-4000-8000-000000000001";
const reportId = "30000000-0000-4000-8000-000000000001";
const content = { ...createInitialPreliminaryReportContent("Participant One", 1), reportPurpose: "Purpose", participantContext: "Context", assessmentContext: "Assessment", informationBasis: "Basis", humanReviewSummary: "Review", reportedFinancialConditions: ["Condition"], reportedStrengths: ["Strength"], reportedPressures: ["Pressure"], evidenceStatus: "Evidence", limitations: "Limits", preliminaryObservations: "Observation", nextSteps: ["Next"], participantNotice: "Notice" };
const transitionRow = { report_id: reportId, assessment_id: assessmentId, report_number: "WPAG-PRR-000001", report_status: "draft", current_version: 1, report_title: content.reportTitle, current_content: content, prepared_at: "2026-08-03T10:00:00Z", submitted_for_review_at: null, reviewed_at: null, approved_at: null, released_at: null, returned_at: null, updated_at: "2026-08-03T10:00:00Z" };
const queueRow = { participant_id: "40000000-0000-4000-8000-000000000001", participant_code: "WPAG-1", participant_name: "Participant One", participant_email: "one@example.com", lifecycle_status: "active", assessment_id: assessmentId, assessment_number: 1, assessment_type: "initial", assessment_submitted_at: "2026-08-03T08:00:00Z", assessment_review_id: "50000000-0000-4000-8000-000000000001", assessment_review_decision: "approved", assessment_review_completed_at: "2026-08-03T09:00:00Z", report_id: null, report_number: null, report_title: null, report_status: null, current_version: null, prepared_by: null, prepared_at: null, reviewed_by: null, reviewed_at: null, approved_by: null, approved_at: null, released_by: null, released_at: null, updated_at: null };

describe("AdminPreliminaryReportService governed boundary", () => {
  beforeEach(resetSupabaseAdminMock);
  it("uses the governed queue RPC", async () => { setRpcResult(successfulResult([queueRow])); await new AdminPreliminaryReportService().listReports(actorId); expect(supabaseAdminSpies.rpc).toHaveBeenCalledWith("list_preliminary_reports", { p_actor_user_id: actorId }); });
  it("maps an eligible queue row", async () => { setRpcResult(successfulResult([queueRow])); await expect(new AdminPreliminaryReportService().listReports(actorId)).resolves.toEqual([expect.objectContaining({ assessmentId, reportStatus: null })]); });
  it("uses the governed detail RPC", async () => { setRpcResult(successfulResult([])); await new AdminPreliminaryReportService().getReport(reportId, actorId); expect(supabaseAdminSpies.rpc).toHaveBeenCalledWith("get_preliminary_report", { p_report_id: reportId, p_actor_user_id: actorId }); });
  it("returns null for missing detail", async () => { setRpcResult(successfulResult([])); await expect(new AdminPreliminaryReportService().getReport(reportId, actorId)).resolves.toBeNull(); });
  it("creates a draft through the transition RPC", async () => { setRpcResult(successfulResult([transitionRow])); await new AdminPreliminaryReportService().transition({ assessmentId, actorUserId: actorId, command: "create_draft", content }); expect(supabaseAdminSpies.rpc).toHaveBeenCalledWith("transition_preliminary_report", expect.objectContaining({ p_assessment_id: assessmentId, p_command: "create_draft", p_content: content })); });
  it("requires complete structured content before submission", async () => { const incomplete = createInitialPreliminaryReportContent("Participant One", 1); await expect(new AdminPreliminaryReportService().transition({ reportId, actorUserId: actorId, command: "submit_for_review", content: incomplete })).rejects.toThrow("Mandatory preliminary report sections are incomplete."); });
  it("passes complete content on submission", async () => { setRpcResult(successfulResult([{ ...transitionRow, report_status: "under_review" }])); await new AdminPreliminaryReportService().transition({ reportId, actorUserId: actorId, command: "submit_for_review", content }); expect(supabaseAdminSpies.rpc).toHaveBeenCalledWith("transition_preliminary_report", expect.objectContaining({ p_command: "submit_for_review", p_content: content })); });
  it("requires a save change summary", async () => { await expect(new AdminPreliminaryReportService().transition({ reportId, actorUserId: actorId, command: "save_draft", content })).rejects.toThrow("Change summary is required."); });
  it("requires return review notes", async () => { await expect(new AdminPreliminaryReportService().transition({ reportId, actorUserId: actorId, command: "return_to_draft" })).rejects.toThrow("Report review notes are required."); });
  it("rejects HTML in structured content", async () => { await expect(new AdminPreliminaryReportService().transition({ reportId, actorUserId: actorId, command: "save_draft", content: { ...content, limitations: "<script>bad</script>" }, changeSummary: "Change" })).rejects.toThrow("Preliminary report content is invalid."); });
  it("normalizes identifiers and text", async () => { setRpcResult(successfulResult([{ ...transitionRow, report_status: "returned" }])); await new AdminPreliminaryReportService().transition({ reportId: ` ${reportId} `, actorUserId: ` ${actorId} `, command: "return_to_draft", reviewNotes: "  Clarify   evidence.  " }); expect(supabaseAdminSpies.rpc).toHaveBeenCalledWith("transition_preliminary_report", expect.objectContaining({ p_report_id: reportId, p_review_notes: "Clarify evidence." })); });
  it("rejects invalid UUIDs", async () => { await expect(new AdminPreliminaryReportService().getReport("invalid", actorId)).rejects.toThrow("Preliminary report ID is required."); });
  it("preserves allowlisted transition errors", async () => { setRpcResult(errorResult("Preliminary report transition is not allowed.", "P1001")); await expect(new AdminPreliminaryReportService().transition({ reportId, actorUserId: actorId, command: "approve" })).rejects.toThrow("Preliminary report transition is not allowed."); });
  it("suppresses raw database diagnostics", async () => { setRpcResult(errorResult("database secret", "XX000")); const promise = new AdminPreliminaryReportService().listReports(actorId); await expect(promise).rejects.toBeInstanceOf(AdminPreliminaryReportServiceError); await expect(promise).rejects.not.toThrow("secret"); });
  it("never uses direct table writes", async () => { setRpcResult(successfulResult([queueRow])); await new AdminPreliminaryReportService().listReports(actorId); expect(supabaseAdminSpies.from).not.toHaveBeenCalled(); });
});
