import { describe, expect, it, vi } from "vitest";
vi.mock("@/lib/supabase/admin", () => ({ supabaseAdmin: { rpc: vi.fn() } }));
import { AdminResearchWave3Service } from "./admin-research-wave3-service";
const id = "10000000-0000-4000-8000-000000000001", actor = "20000000-0000-4000-8000-000000000001", correlation = "30000000-0000-4000-8000-000000000001";
const repository = { getOverview: vi.fn(), reportIncident: vi.fn(), transitionIncident: vi.fn(), restoreIncidentGate: vi.fn(), createSuccessorIncident: vi.fn(), executeFsh: vi.fn(), evaluateRelease: vi.fn() };
const service = () => new AdminResearchWave3Service(repository as never);

describe("AdminResearchWave3Service", () => {
  it("accepts only canonical Incident families, gates, and priorities", async () => { repository.reportIncident.mockResolvedValue(id); await service().reportIncident({ enrollmentId: id, actorUserId: actor, incidentFamily: "INC-FAM-07", incidentType: "EVIDENCE_INTEGRITY", affectedScope: "scope", affectedObjectRefs: [], affectedGates: ["FSH_EXECUTION"], priority: "PROTECTIVE_HOLD_REQUIRED", materialProtectedEffect: true, correlationId: correlation }); expect(repository.reportIncident).toHaveBeenCalledOnce(); });
  it("rejects duplicate gates and unauthorized vocabularies", async () => { await expect(service().reportIncident({ enrollmentId: id, actorUserId: actor, incidentFamily: "INC-FAM-99" as never, incidentType: "X", affectedScope: "scope", affectedObjectRefs: [], affectedGates: ["FSH_EXECUTION", "FSH_EXECUTION"], priority: "LOW" as never, materialProtectedEffect: true, correlationId: correlation })).rejects.toMatchObject({ kind: "invalid" }); expect(repository.reportIncident).not.toHaveBeenCalled(); });
  it("validates all Incident precondition identities", async () => { await expect(service().transitionIncident(id, actor, "RESOLVED", ["INC-PRE-99"], {}, correlation)).rejects.toMatchObject({ kind: "invalid" }); expect(repository.transitionIncident).not.toHaveBeenCalled(); });
  it("requires a complete independent restoration authority", async () => { await expect(service().restoreIncidentGate(id, "FSH_EXECUTION", actor, { authority: "A" }, "RECOVERY", correlation)).rejects.toMatchObject({ kind: "invalid" }); expect(repository.restoreIncidentGate).not.toHaveBeenCalled(); });
  it("rejects restoration self-attestation", async () => { await expect(service().restoreIncidentGate(id, "FSH_EXECUTION", actor, { authority: "A", evidence: "E", independent_reviewer: actor }, "RECOVERY", correlation)).rejects.toMatchObject({ kind: "invalid" }); expect(repository.restoreIncidentGate).not.toHaveBeenCalled(); });
  it("forwards CAP only as metadata for governed FSH", async () => { repository.executeFsh.mockResolvedValue({ result_id: id }); await service().executeFsh({ snapshotId: id, actorUserId: actor, capQualificationMetadata: { qualification: "METADATA_ONLY" }, correlationId: correlation }); expect(repository.executeFsh).toHaveBeenCalledWith({ snapshotId: id, actorUserId: actor, capQualificationMetadata: { qualification: "METADATA_ONLY" }, correlationId: correlation }); });
  it("permits release evaluation only in synthetic environments", async () => { await expect(service().evaluateRelease("production" as never, actor, correlation)).rejects.toMatchObject({ kind: "invalid" }); expect(repository.evaluateRelease).not.toHaveBeenCalled(); });
});
