import { randomUUID } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { getCurrentParticipant, getCurrentUser } from "@/lib/auth/current-participant";
import { AuthenticationError, AuthorizationError } from "@/lib/auth/errors";
import { participantResearchJourneyService, ParticipantResearchJourneyServiceError } from "@/lib/services/participant/participant-research-journey-service";
import { wave4ConsentAcknowledgements } from "@/lib/types/research/research-wave4";
const allowed=new Set(["decision","directConsent","baselineConsent","followUpConsent","acknowledgements"]);
function json(body:object,status:number){return NextResponse.json(body,{status,headers:{"Cache-Control":"private, no-store"}});}
export async function POST(request:NextRequest){try{const user=await getCurrentUser();const participant=await getCurrentParticipant();let body:unknown;try{body=await request.json();}catch{return json({success:false,error:"Request body must be valid JSON."},400);}if(!body||typeof body!=="object"||Array.isArray(body))return json({success:false,error:"Request body must be a JSON object."},400);const v=body as Record<string,unknown>;if(Object.keys(v).some((key)=>!allowed.has(key))||!["GRANTED","DECLINED"].includes(String(v.decision))||typeof v.directConsent!=="boolean"||typeof v.baselineConsent!=="boolean"||typeof v.followUpConsent!=="boolean"||!v.acknowledgements||typeof v.acknowledgements!=="object"||Array.isArray(v.acknowledgements)||Object.keys(v.acknowledgements as object).some((key)=>!wave4ConsentAcknowledgements.includes(key as never)))return json({success:false,error:"Research consent decision is invalid."},400);const result=await participantResearchJourneyService.decide({participantId:participant.participant_id,actorUserId:user.id,decision:v.decision as "GRANTED"|"DECLINED",directConsent:v.directConsent,baselineConsent:v.baselineConsent,followUpConsent:v.followUpConsent,acknowledgements:v.acknowledgements as Record<string,boolean>,correlationId:randomUUID()});return json({success:true,result},201);}catch(error){if(error instanceof AuthenticationError)return json({success:false,error:"Authentication is required."},401);if(error instanceof AuthorizationError)return json({success:false,error:"Participant research controls are unavailable."},403);if(error instanceof ParticipantResearchJourneyServiceError)return json({success:false,error:error.message},error.kind==="invalid"?400:error.kind==="unauthorized"?403:error.kind==="not_found"?404:500);console.error("Research consent decision could not be completed.");return json({success:false,error:"Research consent decision could not be completed."},500);}}
