import { NextRequest } from "next/server";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { AuthenticationError } from "@/lib/auth/errors";
const mocks=vi.hoisted(()=>({getCurrentUser:vi.fn(),getCurrentParticipant:vi.fn(),decide:vi.fn()}));
vi.mock("@/lib/auth/current-participant",()=>({getCurrentUser:mocks.getCurrentUser,getCurrentParticipant:mocks.getCurrentParticipant}));
vi.mock("@/lib/services/participant/participant-research-journey-service",()=>({participantResearchJourneyService:{decide:mocks.decide},ParticipantResearchJourneyServiceError:class extends Error{constructor(readonly kind:string){super("Research consent decision is invalid.");}}}));
import { POST } from "./route";
const request=(body:unknown)=>new NextRequest("http://localhost/api/participant/research-controls/consent",{method:"POST",headers:{"Content-Type":"application/json"},body:typeof body==="string"?body:JSON.stringify(body)});
const acknowledgements={research_purpose:true,voluntary_participation:true,research_only_no_final_state:true,privacy_data_use:true,withdrawal_no_automatic_deletion:true};
const binding={presentationEventId:"50000000-0000-4000-8000-000000000001",presentedArtifactVersion:"HFOS-W4-PARTICIPANT-RESEARCH-CONSENT-v0.1",presentedArtifactSha256:"a".repeat(64),presentedAt:"2026-08-11T12:00:00.000Z"};
const grant={decision:"GRANTED",directConsent:true,baselineConsent:true,followUpScopeDecision:"EXPLICITLY_DECLINED",acknowledgements,...binding};
describe("participant Wave 4 consent route",()=>{
  beforeEach(()=>{vi.resetAllMocks();mocks.getCurrentUser.mockResolvedValue({id:"10000000-0000-4000-8000-000000000001"});mocks.getCurrentParticipant.mockResolvedValue({participant_id:"20000000-0000-4000-8000-000000000001"});mocks.decide.mockResolvedValue({consentStatus:"GRANTED"});});
  it("authenticates before parsing",async()=>{const json=vi.fn();mocks.getCurrentUser.mockRejectedValue(new AuthenticationError());expect((await POST({json} as unknown as NextRequest)).status).toBe(401);expect(json).not.toHaveBeenCalled();});
  it("rejects malformed, unknown, representative, missing-binding, and non-Boolean acknowledgement fields",async()=>{const cases=["{",[],{...grant,representativeId:"x"},{...grant,presentationEventId:undefined},{...grant,acknowledgements:{...acknowledgements,research_purpose:"true"}},{...grant,acknowledgements:{...acknowledgements,research_purpose:1}},{...grant,acknowledgements:{...acknowledgements,research_purpose:null}}];for(const value of cases)expect((await POST(request(value))).status).toBe(400);expect(mocks.decide).not.toHaveBeenCalled();});
  it("rejects missing, Boolean, unanswered, and unsupported follow-up decisions",async()=>{for(const value of [{...grant,followUpScopeDecision:undefined},{...grant,followUpScopeDecision:false},{...grant,followUpScopeDecision:"UNANSWERED"},{...grant,followUpScopeDecision:"LEGACY_UNRESOLVED"},{...grant,followUpConsent:false}])expect((await POST(request(value))).status).toBe(400);expect(mocks.decide).not.toHaveBeenCalled();});
  it.each(["EXPLICITLY_GRANTED","EXPLICITLY_DECLINED"] as const)("accepts %s as an explicit baseline follow-up decision",async(followUpScopeDecision)=>{const response=await POST(request({...grant,followUpScopeDecision}));expect(response.status).toBe(201);expect(mocks.decide).toHaveBeenCalledWith(expect.objectContaining({followUpScopeDecision}));});
  it("derives participant and actor identities server-side and passes the exact presentation binding",async()=>{const response=await POST(request(grant));expect(response.status).toBe(201);expect(mocks.decide).toHaveBeenCalledWith(expect.objectContaining({participantId:"20000000-0000-4000-8000-000000000001",actorUserId:"10000000-0000-4000-8000-000000000001",decision:"GRANTED",followUpScopeDecision:"EXPLICITLY_DECLINED",...binding}));expect(response.headers.get("cache-control")).toContain("no-store");});
});
