import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/supabase/admin", async () => ({ supabaseAdmin: (await import("@/test/mocks/supabase-admin")).supabaseAdminMock }));
import { ParticipantEvidenceFoundationRepository } from "./participant-evidence-foundation-repository";
import { resetSupabaseAdminMock, setRpcResult, setStorageDownloadResult, successfulResult, supabaseAdminSpies } from "@/test/mocks/supabase-admin";

const actorId="20000000-0000-4000-8000-000000000001", assessmentId="10000000-0000-4000-8000-000000000001", sessionId="60000000-0000-4000-8000-000000000001", documentId="30000000-0000-4000-8000-000000000001", reservationId="50000000-0000-4000-8000-000000000001", sha="a".repeat(64), path=`${actorId}/${assessmentId}/${documentId}/v2/40000000-0000-4000-8000-000000000001.pdf`;
const prepareRow={reservation_id:reservationId,document_id:documentId,assessment_id:assessmentId,assessment_session_id:sessionId,storage_bucket:"assessment-evidence",storage_path:path,original_filename:"statement.pdf",mime_type:"application/pdf",file_size_bytes:10,sha256:sha,version_number:2};
const summary={document_id:documentId,assessment_id:assessmentId,assessment_number:1,document_category:"income",document_type:"bank_statement",document_name:"Statement",description:null,original_filename:"statement.pdf",mime_type:"application/pdf",file_size_bytes:10,verification_status:"rejected",verification_notes:"Replace file",current_version:1,submitted_at:"2026-08-03",updated_at:"2026-08-03",can_resubmit:true};

describe("ParticipantEvidenceFoundationRepository",()=>{
 beforeEach(resetSupabaseAdminMock);
 it("maps the participant assessment context RPC",async()=>{setRpcResult(successfulResult([{assessment_id:assessmentId,assessment_number:1,assessment_session_id:sessionId,session_status:"submitted"}]));await expect(new ParticipantEvidenceFoundationRepository().context(actorId)).resolves.toMatchObject({assessmentId,assessmentSessionId:sessionId,sessionStatus:"submitted"});expect(supabaseAdminSpies.rpc).toHaveBeenCalledWith("get_participant_evidence_context",{p_actor_user_id:actorId});});
 it("prepares resubmission through the exact governed RPC",async()=>{setRpcResult(successfulResult([prepareRow]));await expect(new ParticipantEvidenceFoundationRepository().prepareResubmission({documentId,actorUserId:actorId,originalFilename:"statement.pdf",mimeType:"application/pdf",fileSizeBytes:10,sha256:sha})).resolves.toMatchObject({reservationId,versionNumber:2});expect(supabaseAdminSpies.rpc).toHaveBeenCalledWith("prepare_evidence_resubmission",{p_document_id:documentId,p_actor_user_id:actorId,p_original_filename:"statement.pdf",p_mime_type:"application/pdf",p_file_size_bytes:10,p_sha256:sha});});
 it("uploads without overwrite and finalizes through governed resubmission",async()=>{const repository=new ParticipantEvidenceFoundationRepository();const reservation={reservationId,documentId,assessmentId,assessmentSessionId:sessionId,storageBucket:"assessment-evidence" as const,storagePath:path,originalFilename:"statement.pdf",mimeType:"application/pdf" as const,fileSizeBytes:10,sha256:sha,versionNumber:2};await repository.upload(reservation,new Uint8Array(10));expect(supabaseAdminSpies.storageUpload).toHaveBeenCalledWith(path,expect.any(Uint8Array),{contentType:"application/pdf",upsert:false});setRpcResult(successfulResult([{...summary,version_number:2,created_at:"2026-08-04"}]));await repository.finalizeResubmission(actorId,reservation);expect(supabaseAdminSpies.rpc).toHaveBeenLastCalledWith("finalize_evidence_resubmission",{p_reservation_id:reservationId,p_actor_user_id:actorId,p_file_size_bytes:10,p_sha256:sha});expect(supabaseAdminSpies.from).not.toHaveBeenCalled();});
 it("maps safe list and detail projections",async()=>{const repository=new ParticipantEvidenceFoundationRepository();setRpcResult(successfulResult([summary]));const list=await repository.list(actorId);expect(list[0]).toMatchObject({currentVersion:1,canResubmit:true});expect(list[0]).not.toHaveProperty("storagePath");setRpcResult(successfulResult([{...summary,can_download:true,versions:[{version_number:1,original_filename:"statement.pdf",mime_type:"application/pdf",file_size_bytes:10,submitted_at:"2026-08-03"}],verification_history:[{verification_event:"rejected",verification_status:"rejected",participant_notes:"Replace file",event_at:"2026-08-03"}]}]));const detail=await repository.get(documentId,actorId);expect(detail).toMatchObject({versions:[{versionNumber:1}],verificationHistory:[{participantNotes:"Replace file"}]});expect(detail).not.toHaveProperty("sha256");});
 it("rejects unknown status values instead of widening the contract",async()=>{setRpcResult(successfulResult([{...summary,verification_status:"approved"}]));await expect(new ParticipantEvidenceFoundationRepository().list(actorId)).rejects.toMatchObject({operation:"map",kind:"unexpected"});});
 it("resolves download only through RPC and trusted private storage",async()=>{setRpcResult(successfulResult([{document_id:documentId,version_number:1,storage_bucket:"assessment-evidence",storage_path:path,original_filename:"statement.pdf",mime_type:"application/pdf",file_size_bytes:9,sha256:sha}]));const repository=new ParticipantEvidenceFoundationRepository();const reference=await repository.resolveDownload(documentId,actorId,1);expect(supabaseAdminSpies.rpc).toHaveBeenCalledWith("get_participant_evidence_download",{p_document_id:documentId,p_actor_user_id:actorId,p_version_number:1});setStorageDownloadResult(successfulResult(new Blob(["%PDF-test"])));await expect(repository.download(reference)).resolves.toBeInstanceOf(Uint8Array);expect(supabaseAdminSpies.storageFrom).toHaveBeenCalledWith("assessment-evidence");});
});
