import { NextRequest } from "next/server";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AuthenticationError, AuthorizationError } from "@/lib/auth/errors";
const mocks = vi.hoisted(() => ({ requireRole: vi.fn(), getOverview: vi.fn(), reportIncident: vi.fn(), transitionIncident: vi.fn(), restoreIncidentGate: vi.fn(), createSuccessorIncident: vi.fn(), executeFsh: vi.fn(), evaluateRelease: vi.fn() }));
vi.mock("@/lib/auth/authorization", () => ({ requireRole: mocks.requireRole }));
vi.mock("@/lib/services/admin/admin-research-wave3-service", () => ({ ResearchWave3ServiceError: class ResearchWave3ServiceError extends Error {}, adminResearchWave3Service: mocks }));
import { GET, POST } from "./route";
const context = { params: Promise.resolve({ participantId: "10000000-0000-4000-8000-000000000001" }) };
const request = (body: unknown) => new NextRequest("http://localhost/api/admin/participants/id/research-wave3", { method: "POST", headers: { "Content-Type": "application/json" }, body: typeof body === "string" ? body : JSON.stringify(body) });
beforeEach(() => { vi.resetAllMocks(); mocks.requireRole.mockResolvedValue({ auth_user_id: "20000000-0000-4000-8000-000000000001" }); mocks.getOverview.mockResolvedValue(null); mocks.reportIncident.mockResolvedValue("incident"); mocks.transitionIncident.mockResolvedValue({ transition_applied: true }); });
describe("admin Wave 3 research route", () => {
  it("requires administrator authorization before parsing", async () => { const json = vi.fn(); mocks.requireRole.mockRejectedValue(new AuthenticationError()); expect((await POST({ json } as unknown as NextRequest, context)).status).toBe(401); expect(json).not.toHaveBeenCalled(); mocks.requireRole.mockRejectedValueOnce(new AuthorizationError()); expect((await GET(new NextRequest("http://localhost"), context)).status).toBe(403); });
  it("serves only a private no-store internal overview", async () => { const response = await GET(new NextRequest("http://localhost"), context); expect(response.status).toBe(200); expect(response.headers.get("cache-control")).toContain("no-store"); expect(mocks.getOverview).toHaveBeenCalledWith("10000000-0000-4000-8000-000000000001", "20000000-0000-4000-8000-000000000001"); });
  it("rejects malformed, unsupported, and non-object commands", async () => { expect((await POST(request("{"), context)).status).toBe(400); expect((await POST(request([]), context)).status).toBe(400); expect((await POST(request({ command: "activate_production", correlationId: "x" }), context)).status).toBe(400); expect((await POST(request({ command: "evaluate_release", correlationId: "x", environment: "synthetic_test", open: true }), context)).status).toBe(400); });
  it("passes a canonical Incident report with server actor attribution", async () => { const body = { command: "report_incident", correlationId: "30000000-0000-4000-8000-000000000001", enrollmentId: "40000000-0000-4000-8000-000000000001", incidentFamily: "INC-FAM-07", incidentType: "EVIDENCE_INTEGRITY", occurrenceTime: null, affectedScope: "scope", affectedObjectRefs: [], affectedGates: ["FSH_EXECUTION"], priority: "PROTECTIVE_HOLD_REQUIRED", materialProtectedEffect: true }; expect((await POST(request(body), context)).status).toBe(200); expect(mocks.reportIncident).toHaveBeenCalledWith(expect.objectContaining({ actorUserId: "20000000-0000-4000-8000-000000000001", incidentFamily: "INC-FAM-07" })); });
  it("rejects unapproved Incident and State vocabularies", async () => { const base = { command: "transition_incident", correlationId: "30000000-0000-4000-8000-000000000001", incidentId: "40000000-0000-4000-8000-000000000001", satisfiedPreconditions: [], reviewPayload: {} }; for (const requestedStatus of ["REOPENED", "Stable", "Fragile"]) expect((await POST(request({ ...base, requestedStatus }), context)).status).toBe(400); expect(mocks.transitionIncident).not.toHaveBeenCalled(); });
  it("never provides a real, Pilot, or Production release command", async () => { for (const environment of ["controlled_research", "pilot", "production"]) expect((await POST(request({ command: "evaluate_release", correlationId: "30000000-0000-4000-8000-000000000001", environment }), context)).status).toBe(400); expect(mocks.evaluateRelease).not.toHaveBeenCalled(); });
});
