import { NextRequest } from "next/server";import{beforeEach,describe,expect,it,vi}from"vitest";import{AuthenticationError,AuthorizationError}from"@/lib/auth/errors";
const mocks=vi.hoisted(()=>({requireRole:vi.fn(),capture:vi.fn(),summary:vi.fn()}));
vi.mock("@/lib/auth/authorization",()=>({requireRole:mocks.requireRole}));vi.mock("@/lib/services/admin/admin-hfos-measurement-service",()=>({captureHfosMeasurement:mocks.capture,loadAdminHfosMeasurementSummary:mocks.summary}));
import{GET,POST}from"./route";
const context={params:Promise.resolve({participantId:"c2000000-0000-4000-8000-000000000001"})};
const request=(body:unknown)=>new NextRequest("http://localhost/api/admin/participants/id/measurements",{method:"POST",headers:{"Content-Type":"application/json"},body:typeof body==="string"?body:JSON.stringify(body)});
beforeEach(()=>{vi.resetAllMocks();mocks.requireRole.mockResolvedValue({auth_user_id:"actor"});mocks.capture.mockResolvedValue({success:true,data:{runId:"run"}});mocks.summary.mockResolvedValue({success:true,data:null});});
describe("admin HFOS measurement route",()=>{
 it("authorizes GET and returns no-store metadata",async()=>{const response=await GET(new NextRequest("http://localhost"),context);expect(response.status).toBe(200);expect(response.headers.get("cache-control")).toBe("no-store");expect(mocks.summary).toHaveBeenCalledWith("c2000000-0000-4000-8000-000000000001");});
 it("maps authentication and authorization failures",async()=>{mocks.requireRole.mockRejectedValueOnce(new AuthenticationError());expect((await GET(new NextRequest("http://localhost"),context)).status).toBe(401);mocks.requireRole.mockRejectedValueOnce(new AuthorizationError());expect((await POST(request({}),context)).status).toBe(403);});
 it("authorizes before parsing POST JSON",async()=>{const json=vi.fn();mocks.requireRole.mockRejectedValue(new AuthenticationError());expect((await POST({json}as unknown as NextRequest,context)).status).toBe(401);expect(json).not.toHaveBeenCalled();});
 it("rejects malformed and non-object JSON",async()=>{expect((await POST(request("{"),context)).status).toBe(400);expect((await POST(request([]),context)).status).toBe(400);});
 it("rejects unsupported client-controlled fields",async()=>{for(const field of ["generatedBy","engineVersion","formulaSetVersion","status","inputHash","participantId"]){expect((await POST(request({assessmentId:"a",executionReason:"r",idempotencyKey:"k",[field]:"x"}),context)).status).toBe(400);}});
 it("requires the three approved string fields",async()=>{expect((await POST(request({assessmentId:1,executionReason:"r",idempotencyKey:"k"}),context)).status).toBe(400);});
 it("passes only route participant and approved body fields",async()=>{await POST(request({assessmentId:"assessment",executionReason:"capture",idempotencyKey:"key"}),context);expect(mocks.capture).toHaveBeenCalledWith({participantId:"c2000000-0000-4000-8000-000000000001",assessmentId:"assessment",executionReason:"capture",idempotencyKey:"key"});});
 it("returns 201 for capture and maps conflict safely",async()=>{expect((await POST(request({assessmentId:"a",executionReason:"r",idempotencyKey:"k"}),context)).status).toBe(201);mocks.capture.mockResolvedValue({success:false,error:"Measurement idempotency key conflicts with another source."});expect((await POST(request({assessmentId:"a",executionReason:"r",idempotencyKey:"k"}),context)).status).toBe(409);});
 it("suppresses unexpected diagnostics",async()=>{vi.spyOn(console,"error").mockImplementation(()=>undefined);mocks.capture.mockRejectedValue(new Error("raw database secret"));const response=await POST(request({assessmentId:"a",executionReason:"r",idempotencyKey:"k"}),context);expect(response.status).toBe(500);expect(JSON.stringify(await response.json())).not.toContain("raw database");});
});
