"use client";
import Link from"next/link";import{useEffect,useMemo,useRef,useState}from"react";import{assessmentRegistry,HFOS_VERSION}from"@/lib/assessment/assessment-registry";import type{AssessmentActionResult,CurrentParticipantAssessment}from"@/lib/types/participant/assessment";
const acknowledgements=["I confirm these responses are accurate to the best of my knowledge.","I understand responses remain participant-provided and unverified.","I understand this workflow does not provide financial advice.","I understand that no HFOS score, diagnosis, recommendation, or report is generated."];
export default function ReviewSubmitPage(){const[assessment,setAssessment]=useState<CurrentParticipantAssessment|null>(null);const[accepted,setAccepted]=useState(()=>acknowledgements.map(()=>false));const[message,setMessage]=useState("");const lock=useRef(false);
 useEffect(()=>{void fetch("/api/participant/assessment",{cache:"no-store"}).then(r=>r.json()).then((r:AssessmentActionResult<CurrentParticipantAssessment|null>)=>{if(r.success)setAssessment(r.assessment??null);else setMessage(r.formError??"The assessment could not be loaded.");}).catch(()=>setMessage("The assessment could not be loaded."));},[]);
 const complete=useMemo(()=>assessment?assessmentRegistry.every(m=>assessment.module_progress[m.key]?.status==="complete"):false,[assessment]);const submitted=assessment?.session_status==="submitted";
 async function submit(){if(lock.current||!complete||!accepted.every(Boolean)||submitted)return;lock.current=true;try{const response=await fetch("/api/participant/assessment/submit",{method:"POST"});const result=await response.json() as AssessmentActionResult<CurrentParticipantAssessment>;if(result.success&&result.assessment){setAssessment(result.assessment);setMessage("Assessment submitted successfully.");}else setMessage(result.formError??"The assessment could not be submitted.");}catch{setMessage("The assessment could not be submitted.");}finally{lock.current=false;}}
 return <main className="min-h-screen bg-[#f4f2ed]"><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><header className="border-b border-black pb-8"><p className="text-xs uppercase tracking-[.25em]">Review and Submit</p><h1 className="mt-5 font-serif text-5xl">Review durable responses</h1><p className="mt-5">Assessment version {assessment?.assessment_version??"1.0"} · Framework {assessment?.hfos_version??HFOS_VERSION} (non-diagnostic)</p><p className="mt-3 text-black/60">All information is participant-provided and unverified.</p></header>
 {!assessment?<p className="py-10">Start an assessment before review.</p>:<>{assessmentRegistry.map(module=><section key={module.key} className="border-b border-black/20 py-8"><div className="flex justify-between gap-4"><h2 className="font-serif text-3xl">{module.title}</h2><span className="capitalize">{assessment.module_progress[module.key]?.status.replaceAll("_"," ")}</span></div><dl className="mt-5 grid gap-3">{Object.entries(assessment.answers[module.key]??{}).map(([key,answer])=><div key={key} className="grid gap-2 sm:grid-cols-2"><dt className="text-sm text-black/60">{key.slice(module.key.length+1).replaceAll("_"," ")}</dt><dd className="break-words">{typeof answer.value==="object"?JSON.stringify(answer.value):String(answer.value)}</dd></div>)}</dl><Link href={module.route} className="mt-5 inline-block underline">{submitted?"View module":"Review module"}</Link></section>)}
 {!submitted&&<section className="py-8"><h2 className="font-serif text-3xl">Acknowledgements</h2>{acknowledgements.map((label,index)=><label key={label} className="mt-4 flex gap-3"><input type="checkbox" checked={accepted[index]} onChange={()=>setAccepted(current=>current.map((value,i)=>i===index?!value:value))}/><span>{label}</span></label>)}<button disabled={!complete||!accepted.every(Boolean)} onClick={()=>void submit()} className="mt-8 bg-black px-6 py-3 text-white disabled:opacity-35">Submit Assessment</button>{!complete&&<p className="mt-3 text-sm text-red-700">Complete all required modules before submission.</p>}</section>}{submitted&&<p className="my-8 border border-black bg-black p-5 text-white">Submitted {assessment.submitted_at?new Date(assessment.submitted_at).toLocaleString():""}. Responses are now read-only.</p>}</>}{message&&<p role="status" className="my-5 border border-black p-4">{message}</p>}</div></main>}
