"use client";
import Link from "next/link";import{useEffect,useMemo,useRef,useState}from"react";
import{assessmentRegistry,HFOS_VERSION}from"@/lib/assessment/assessment-registry";
import type{AssessmentActionResult,CurrentParticipantAssessment}from"@/lib/types/participant/assessment";
export default function AssessmentDashboardPage(){
 const[assessment,setAssessment]=useState<CurrentParticipantAssessment|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const lock=useRef(false);
 useEffect(()=>{void fetch("/api/participant/assessment",{cache:"no-store"}).then(r=>r.json()).then((r:AssessmentActionResult<CurrentParticipantAssessment|null>)=>{if(r.success)setAssessment(r.assessment??null);else setMessage(r.formError??"The assessment could not be loaded.");}).catch(()=>setMessage("The assessment could not be loaded.")).finally(()=>setLoading(false));},[]);
 const completed=useMemo(()=>assessment?assessmentRegistry.filter(m=>assessment.module_progress[m.key]?.status==="complete").length:0,[assessment]);
 async function start(){if(lock.current)return;lock.current=true;setMessage("");try{const response=await fetch("/api/participant/assessment/start",{method:"POST"});const result=await response.json() as AssessmentActionResult<CurrentParticipantAssessment>;if(result.success&&result.assessment)setAssessment(result.assessment);else setMessage(result.formError??"The assessment could not be started.");}catch{setMessage("The assessment could not be started.");}finally{lock.current=false;}}
 return <main className="min-h-screen bg-[#f4f2ed] text-black"><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8">
  <header className="border-b border-black pb-8"><p className="text-xs font-semibold uppercase tracking-[.25em] text-black/55">Participant Portal · Assessment</p><h1 className="mt-5 font-serif text-5xl">Financial assessment</h1><p className="mt-5 max-w-3xl leading-7 text-black/65">Responses are saved durably as participant-provided, unverified information. Framework reference {HFOS_VERSION} is non-diagnostic.</p></header>
  {loading?<p className="py-12">Loading assessment…</p>:!assessment?<section className="py-12"><h2 className="font-serif text-3xl">No assessment started</h2><button onClick={()=>void start()} className="mt-6 bg-black px-6 py-3 text-white">Start Assessment</button></section>:<>
   <section className="my-8 grid gap-4 border border-black bg-black p-6 text-white sm:grid-cols-3"><div><p className="text-xs uppercase text-white/55">Status</p><p className="mt-2 text-xl capitalize">{assessment.session_status.replaceAll("_"," ")}</p></div><div><p className="text-xs uppercase text-white/55">Modules</p><p className="mt-2 text-xl">{completed} of 6 complete</p></div><div><p className="text-xs uppercase text-white/55">Updated</p><p className="mt-2 text-xl">{new Date(assessment.updated_at).toLocaleString()}</p></div></section>
   <section className="grid gap-4 sm:grid-cols-2">{assessmentRegistry.map(module=><Link key={module.key} href={module.route} className="border border-black/25 p-6"><p className="text-xs uppercase tracking-widest">Module {module.order}</p><h2 className="mt-3 font-serif text-2xl">{module.title}</h2><p className="mt-4 capitalize">{assessment.module_progress[module.key]?.status.replaceAll("_"," ")}</p></Link>)}</section>
   <div className="mt-8"><Link href="/participant/assessment/review-submit" className={`inline-block px-6 py-3 ${completed===6?"bg-black text-white":"border border-black/30 text-black/50"}`}>Review and Submit</Link>{completed<6&&<p className="mt-3 text-sm text-black/60">Submission is available after all six modules are complete.</p>}{assessment.submitted_at&&<p className="mt-3">Submitted {new Date(assessment.submitted_at).toLocaleString()}</p>}</div>
  </>}{message&&<p role="alert" className="mt-6 border border-red-700 p-4 text-red-700">{message}</p>}
 </div></main>;
}
