// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import "@testing-library/jest-dom/vitest";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import ParticipantProfileClient from "./ParticipantProfileClient";
import type { CurrentParticipantProfile } from "@/lib/types/participant/participant-profile";

const participant={participant_id:"p1",participant_code:"WPAG-1",lifecycle_status:"active",research_status:"enrolled",enrollment_date:null,profile_completed:false} as const;
const profile:CurrentParticipantProfile={firstName:"Asha",middleName:"",lastName:"Rao",preferredName:"",dateOfBirth:"1990-01-01",gender:"female",maritalStatus:"single",email:"a@test.local",phoneCountryCode:"+91",phoneNumber:"9876543210",countryCode:"IN",state:"KA",district:"",city:"Bengaluru",postalCode:"560001",educationLevel:"",occupation:"",employmentStatus:"employed",householdSize:2,dependents:0,emergencyContactName:"Ravi",emergencyContactRelationship:"Sibling",emergencyContactPhone:"+91 9876543211",profileCompleted:false,profileCompletedAt:null,updatedAt:"2026-01-01T00:00:00Z"};

describe("participant profile interactions",()=>{
 beforeEach(()=>{Element.prototype.scrollIntoView=vi.fn();vi.stubGlobal("fetch",vi.fn());});
 afterEach(()=>{cleanup();vi.unstubAllGlobals();});
 it("hides save while pristine and exposes actionable incomplete completion",()=>{render(<ParticipantProfileClient participant={participant} initialProfile={{...profile,city:""}}/>);expect(screen.queryByRole("button",{name:"Save Progress"})).toBeNull();expect(screen.getByRole("button",{name:"Complete Profile"})).toBeDisabled();expect(screen.getByText(/required field remains/)).toBeTruthy();});
 it("shows enabled save for a valid dirty draft and can revert",async()=>{const user=userEvent.setup();render(<ParticipantProfileClient participant={participant} initialProfile={profile}/>);await user.type(screen.getByLabelText("Preferred name"),"Ash");expect(screen.getByRole("button",{name:"Save Progress"})).toBeEnabled();await user.click(screen.getByRole("button",{name:"Cancel and revert changes"}));expect(screen.queryByRole("button",{name:"Save Progress"})).toBeNull();});
 it("posts the exact visible form and loaded version for completion",async()=>{const user=userEvent.setup();vi.mocked(fetch).mockResolvedValue(new Response(JSON.stringify({success:true,profile:{...profile,preferredName:"Ash",profileCompleted:true,profileCompletedAt:"2026-01-02T00:00:00Z",updatedAt:"2026-01-02T00:00:00Z"}}),{status:200}));render(<ParticipantProfileClient participant={participant} initialProfile={profile}/>);await user.type(screen.getByLabelText("Preferred name"),"Ash");await user.click(screen.getByRole("button",{name:"Complete Profile"}));await waitFor(()=>expect(fetch).toHaveBeenCalledTimes(1));const init=vi.mocked(fetch).mock.calls[0][1] as RequestInit;expect(JSON.parse(init.body as string)).toMatchObject({profile:{preferredName:"Ash",firstName:"Asha"},expectedUpdatedAt:profile.updatedAt});expect(screen.getByText("Profile completed successfully.")).toBeTruthy();await waitFor(()=>expect(document.activeElement?.getAttribute("role")).toBe("status"));});
 it("never submits dirty invalid completion and immediately rejects future DOB",async()=>{const user=userEvent.setup();render(<ParticipantProfileClient participant={participant} initialProfile={profile}/>);const dob=screen.getByLabelText(/Date of birth/);expect(dob).toHaveAttribute("max");fireEvent.change(dob,{target:{value:"2099-01-01"}});expect(screen.getByRole("button",{name:"Complete Profile"})).toBeDisabled();expect(screen.getByRole("button",{name:"Save Progress"})).toBeDisabled();expect(fetch).not.toHaveBeenCalled();await user.click(screen.getByRole("button",{name:"Complete Profile"}));expect(fetch).not.toHaveBeenCalled();});
 it("locks duplicate submission and fields to the submitted snapshot",async()=>{const user=userEvent.setup();let resolve!: (value:Response)=>void;vi.mocked(fetch).mockReturnValue(new Promise((done)=>{resolve=done;}));render(<ParticipantProfileClient participant={participant} initialProfile={profile}/>);const complete=screen.getByRole("button",{name:"Complete Profile"});await user.click(complete);await user.click(complete);expect(fetch).toHaveBeenCalledTimes(1);expect(screen.getByLabelText(/First name/)).toBeDisabled();resolve(new Response(JSON.stringify({success:true,profile:{...profile,profileCompleted:true}}),{status:200}));await screen.findByText("Profile completed successfully.");});
 it("surfaces a conflict contract and focuses the error summary",async()=>{const user=userEvent.setup();vi.mocked(fetch).mockResolvedValue(new Response(JSON.stringify({success:false,errorCode:"conflict",formError:"This profile was updated in another session. Refresh the page before trying again."}),{status:409}));render(<ParticipantProfileClient participant={participant} initialProfile={profile}/>);await user.click(screen.getByRole("button",{name:"Complete Profile"}));const text=await screen.findByText(/updated in another session/);const summary=text.closest("div")!;await waitFor(()=>expect(document.activeElement).toBe(summary));});
});
